version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: circleci-analyticalmetlx-{{checksum "pom.xml"}}  
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-analyticalmetlx-{{checksum "pom.xml"}}  
      - run: sbt test
      - store_test_results:

workflows:
  version: 2
    build-and-deploy:
      jobs:
        - build
        - test  
